[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]
edition = "2018"
build = "build.rs"

[lib]
name = "kvproto"
path = "src/lib.rs"

[features]
default = ["lib-rust-protobuf"]
lib-rust-protobuf = ["protobuf"]
lib-prost = ["prost", "prost-derive", "bytes"]
regenerate = []

[dependencies]
protobuf = { version = "~2.0", optional = true }
prost = { version = "0.4", optional = true }
prost-derive = { version = "0.4", optional = true }
bytes = { version = "0.4.11", optional = true }
futures = "0.1"
grpcio = "0.4"
raft = "0.4"

[build-dependencies]
kvproto-build = { git = "https://github.com/nrc/kvproto-build.git" }
